Timing Consistency Between Toolchains
SymbiFlow/fpga-tool-perf pull request #203
Opened 2020-08-03 20:54 UTC by ryancj14

I found two issues with timing consistency that I have addressed with this pull request.

Each toolchain's runtime includes a `prepare` time, as well as a `self.add_runtimes()`. The problem is that while `prepare` time is included in symbiflow's `total` time, it is not included in vivado's total time. The other inconsistency is that the `self.add_runtimes()` function is included in symbiflow's `total` but not in vivado's.

These are my solutions:
1. In `symbiflow.py`, I removed the `self.add_runtimes()` from the `total` runtime, since it isn't actually a part of the running toolchain, simply a gathering of runtimes. This simply meant deleting a tab from it, so it takes place after (and not during) the `with Timed(self, 'total'):` code block.
2. In `vivado.py`, I moved the `with Timed(self, 'total'):` block to the front of the function, to include prepare. It looks confusing through Github, but I really just moved that one line and tabbed the `with Timed(self, 'prepare'):` block to be a part of it.

This clears up all the consistency issues that I know of.

2020-08-03 20:59 UTC, ryancj14 commented
The only other issue I would like to discuss in regards to this pull request is the `nop` timing.

In toolchain.py, 
this is the code that determines the runtime recorded under `nop`. It takes place in the toolchain.py `__init__` definition.
```
with Timed(self, 'nop'):
    subprocess.check_call("true", shell=True, cwd=self.out_dir)
```

To me, it seems to simply call the true command in the bash shell, and it is the same for every toolchain. Is this correct? and why is this? Is it simply a way to judge the speed of the computer you are working with before you start the toolchain? What is the importance of having this `nop` in this spot? 

An answer to this would be much appreciated. If we don't need `nop` in our timing, I can remove those lines. Thanks.

2020-10-12 23:54 UTC, ryancj14 commented
This is ready to be merged.

2020-10-13 11:17 UTC, acomodi requested changes
LGTM. apart for small changes to formatting.

2020-10-13 11:17 UTC, acomodi commented on symbiflow.py
> +        self.add_runtimes()
Let's add a new-line between different Timed scopes, just to make it clearer (same applies to the other toolchains.

2020-10-15 11:15 UTC, acomodi approved these changes
LGTM

2020-10-15 11:15 UTC, merged