exhaust.py - saving table output to a text file
SymbiFlow/fpga-tool-perf pull request #266
Opened 2020-11-13 00:39 UTC by ryancj14

I've found the table output to be interesting, and to be able to reference the output of the last exhaust.py run could be useful. This saves the table to a text file called `exhaust_output.txt` inside of whichever directory is set by `--out-prefix`, the default and usual location being `build/_exhaust-runs/exhaust_output.txt`.

2021-01-18 19:41 UTC, ryancj14 commented
This pr is ready to merge. Let me know if it needs to be different or doesn't seem to be a needed change.

2021-08-24 21:34 UTC, ryancj14 commented
I will no longer be working in the realm of student research related to SymbiFlow, so you can do with this PR as you wish. It is ready to be merged if you would like. Thanks.

2021-08-25 00:29 UTC, mithro commented
@acomodi - Any reason you didn't review this?

2021-08-25 07:21 UTC, acomodi commented
@mithro I think I have lost track of this PR, I'll take a look at it

2021-09-29 13:12 UTC, acomodi requested changes
I believe that duplication of code to save the table data in an output file might not be necessary.

A possible solution might be to add an argument to determine whether the table will be displayed or saved on file and avoid duplicating code.

Given that this PR is outdated, I'll close it for now.

2021-09-29 13:12 UTC, closed without merging