Add hamsternz display port
SymbiFlow/fpga-tool-perf pull request #60
Opened 2020-04-14 11:39 UTC by wtatarski

2020-04-14 14:31 UTC, mithro commented
This looks like a pretty great test case. Can you also update the doc at https://docs.google.com/document/d/16L50pyS3RjYStvRKRoWyVac7NoZKyu45fpPQXJqeKYo/edit ?

2020-04-14 14:32 UTC, mithro commented
All third party code should be under the `third_party` directory. Can we just use a git submodule here?

2020-04-15 10:17 UTC, wtatarski commented
Added hamsternz-displayport as submodule.

2020-04-16 19:40 UTC, mithro commented
@acomodi - Just wanted to make sure that you are checking these imports comply with the standards set out in https://github.com/SymbiFlow/ideas/issues/47 !
(PS We probably should have an automated system which checks this....)

2020-04-16 21:33 UTC, acomodi commented
@mithro I am actually unsure how to treat the submodules regarding licensing. The hamsternz display port is unmodified and there are no modifications on the source files. For submodules we have no control over their license and the README.fpga-tool-perf should not be needed.

2020-10-13 11:28 UTC, acomodi requested changes
Comment in

2020-10-13 11:28 UTC, acomodi commented on src/hamsternz-displayport/constr/vivado-yosys/xc7_a200t_sbg484-1_nexys.xdc
> +##Clock Signal
This shouldn't be required anymore

2020-10-14 06:05 UTC, kamilrakoczy commented on src/hamsternz-displayport/constr/vivado-yosys/xc7_a200t_sbg484-1_nexys.xdc
> +##Clock Signal
Removed.

2020-10-14 08:21 UTC, acomodi approved these changes
LGTM

2020-10-14 08:21 UTC, merged